import Foundation

/// Represents a request to execute a specific tool with structured arguments.
/// Tool calls are generated by the LLM (or other sources) and validated before execution.
public struct ToolCall: Sendable, Equatable {
    /// Identifier of the tool to execute.
    public let toolIdentifier: ToolIdentifier
    
    /// Structured arguments for the tool execution.
    /// Keys must match parameter names defined in ToolDefinition.
    public let arguments: [String: Sendable]
    
    /// Session identifier for this tool call.
    /// Used to prevent stale requests from executing tools and mutating state.
    public let sessionID: UUID
    
    /// Correlation identifier for tracking tool execution through the system.
    /// Useful for logging, debugging, and async result matching.
    public let correlationID: UUID
    
    public init(
        toolIdentifier: ToolIdentifier,
        arguments: [String: Sendable] = [:],
        sessionID: UUID,
        correlationID: UUID = UUID()
    ) {
        self.toolIdentifier = toolIdentifier
        self.arguments = arguments
        self.sessionID = sessionID
        self.correlationID = correlationID
    }
    
    /// Validates that required parameters are present and non-empty in arguments.
    /// - Parameter definition: The tool definition to validate against
    /// - Returns: Validation error if required parameters are missing or invalid, nil if valid
    public func validateAgainst(_ definition: ToolDefinition) -> ToolValidationError? {
        for parameter in definition.parameters where parameter.isRequired {
            guard let value = arguments[parameter.name] else {
                return ToolValidationError.missingRequiredParameter(parameter.name)
            }
            
            // Validate string parameters are not empty or whitespace-only
            if parameter.type == .string, let stringValue = value as? String {
                let trimmed = stringValue.trimmingCharacters(in: .whitespacesAndNewlines)
                if trimmed.isEmpty {
                    return ToolValidationError.emptyParameter(parameter.name)
                }
            }
        }
        return nil
    }
    
    /// Custom equality implementation that compares tool identifier, session ID, and correlation ID.
    /// Arguments dictionary is compared by count only due to Sendable type limitations.
    public static func == (lhs: ToolCall, rhs: ToolCall) -> Bool {
        lhs.toolIdentifier == rhs.toolIdentifier &&
        lhs.sessionID == rhs.sessionID &&
        lhs.correlationID == rhs.correlationID &&
        lhs.arguments.count == rhs.arguments.count
    }
}

/// Validation errors for tool calls.
public enum ToolValidationError: Error, Equatable {
    case missingRequiredParameter(String)
    case emptyParameter(String)
    case invalidParameterType(String, expected: ToolParameterType)
    case unknownParameter(String)
}